"""create analysis table

Revision ID: 539273064a3d
Revises: 8c7cfc8fba79
Create Date: 2023-09-23 16:26:30.863813

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "539273064a3d"
down_revision: Union[str, None] = "8c7cfc8fba79"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "analysis",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("telegram_img_id", sa.String(), nullable=False),
        sa.Column("telegram_conversation_id", sa.String(), nullable=False),
        sa.Column("model_predicted_fruit_type_id", sa.Integer(), nullable=True),
        sa.Column("user_predicted_fruit_type_id", sa.Integer(), nullable=True),
        sa.Column(
            "model_predicted_fruit_maturation_stage_id", sa.Integer(), nullable=True
        ),
        sa.Column(
            "user_predicted_fruit_maturation_stage_id", sa.Integer(), nullable=True
        ),
        sa.Column("user_approval", sa.Boolean(), nullable=True),
        sa.ForeignKeyConstraint(
            ["model_predicted_fruit_maturation_stage_id"],
            ["fruit_maturation_stage.id"],
        ),
        sa.ForeignKeyConstraint(
            ["model_predicted_fruit_type_id"],
            ["fruit_type.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_predicted_fruit_maturation_stage_id"],
            ["fruit_maturation_stage.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_predicted_fruit_type_id"],
            ["fruit_type.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("telegram_img_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("analysis")
    # ### end Alembic commands ###
