"""Adding constraints to column name in fruit_type and fruit_maturation_stage

Revision ID: 8c7cfc8fba79
Revises: ebd34b05cdc5
Create Date: 2023-09-22 21:30:50.618359

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "8c7cfc8fba79"
down_revision: Union[str, None] = "ebd34b05cdc5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, "fruit_maturation_stage", ["name"])
    op.create_unique_constraint(None, "fruit_type", ["name"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "fruit_type", type_="unique")
    op.drop_constraint(None, "fruit_maturation_stage", type_="unique")
    # ### end Alembic commands ###
