"""add audit columns to analysis table

Revision ID: af3e55ab67d2
Revises: 539273064a3d
Create Date: 2023-11-10 17:27:00.683479

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'af3e55ab67d2'
down_revision: Union[str, None] = '539273064a3d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('analysis', sa.Column('model_fruit_type_name', sa.String(), server_default='UNKNOWN', nullable=False))
    op.add_column('analysis', sa.Column('model_fruit_stage_name', sa.String(), nullable=True))
    op.add_column('analysis', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('analysis', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('analysis', 'updated_at')
    op.drop_column('analysis', 'created_at')
    op.drop_column('analysis', 'model_fruit_stage_name')
    op.drop_column('analysis', 'model_fruit_type_name')
    # ### end Alembic commands ###
