"""Create fruit_maturation_stage table

Revision ID: ebd34b05cdc5
Revises: 1b11d512b24a
Create Date: 2023-09-22 20:42:18.721734

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ebd34b05cdc5'
down_revision: Union[str, None] = '1b11d512b24a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fruit_maturation_stage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('fruit_maturation_stage')
    # ### end Alembic commands ###
